version: '2'
services:
  security:
    image: node:11
    ports:
     - "8000:8000"
     - "3000:3000"
    depends_on:
     - db
    environment:
     - DATABASE_HOST=db
     - PORT=8000
    volumes:
     - ../:/app/api
     - ../../react-ignite-coreui:/app/client
    working_dir: /app/api
    command: bash -c "sh start.sh"
    restart: always
  db:
    image: mysql:5.6
    environment:
      - MYSQL_ALLOW_EMPTY_ROOT=true
      - MYSQL_DATABASE=binance
      - MYSQL_USER=root
      - MYSQL_PASSWORD=laravel
    ports:
     - "33061:3306"
