version: '2'
services:
  security:
    image: node:11
    ports:
     - "8000:8000"
    depends_on:
     - db
    environment:
     - DATABASE_HOST=db
     - PORT=8000
    volumes:
     - ../:/app/api
    working_dir: /app/api
    command: bash -c "yarn install && yarn start"
    restart: always
  db:
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD laravel
      - MYSQL_DATABASE binance
      - MYSQL_USER root
      - MYSQL_PASSWORD laravel
    ports:
     - "33061:3306"